"""Closed expected-failure vocabulary for skill results."""

from enum import Enum


class FailureCode(str, Enum):
    INVALID_INPUT = "INVALID_INPUT"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    RESOURCE_BUSY = "RESOURCE_BUSY"
    RESOURCE_INCOMPATIBLE = "RESOURCE_INCOMPATIBLE"
    PRECONDITION_FALSE = "PRECONDITION_FALSE"
    PRECONDITION_UNKNOWN = "PRECONDITION_UNKNOWN"
    OBSERVATION_UNAVAILABLE = "OBSERVATION_UNAVAILABLE"
    OBSERVATION_STALE = "OBSERVATION_STALE"
    GEOMETRY_BINDING_MISSING = "GEOMETRY_BINDING_MISSING"
    CALIBRATION_MISMATCH = "CALIBRATION_MISMATCH"
    SNAPSHOT_REQUIRED = "SNAPSHOT_REQUIRED"
    SNAPSHOT_STALE = "SNAPSHOT_STALE"
    CAPABILITY_UNAVAILABLE = "CAPABILITY_UNAVAILABLE"
    PLAN_FAILED = "PLAN_FAILED"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"
    SAFETY_REJECTED = "SAFETY_REJECTED"
    TIMED_OUT = "TIMED_OUT"
    CANCELLED = "CANCELLED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
